#pragma config(Sensor, S1,     light,          sensorLightActive)
#pragma config(Sensor, S2,     light2,         sensorI2CHiTechnicColor)
#pragma config(Sensor, S3,     Sonar,          sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int count2 = 0;
	float vel = 20;
	float accel = 0.0;
	while(1)
	{
			//izquierdo //5 madera ,10 negro
			//derecho 54 madera ,45 negro
			if(SensorValue(light) < 45)
			{
				vel = 20;
				accel = 0;

				motor[motorA] = -25;
				motor[motorB] = 15;
				wait1Msec(150);
				continue;
			}
			if(SensorValue(light2) == 0 || SensorValue(light2) == 17 )
			{
				vel = 20;
				accel = 0;
				//writeDebugStreamLine("%d ",cont);
			  motor[motorB] = -25;
			  motor[motorA] = 15;
			  wait1Msec(150);

			  continue;
			}

			if(accel <= 55)
			{
				writeDebugStreamLine("si");
				count2 ++;
				writeDebugStreamLine("%d", count2);
				if(count2 >= 100 )
				{
					count2 = 0;
					accel+= 1.5;
				}
		  }
		  //vel = vel+accel;
			motor[motorA] = vel+accel;
			motor[motorB] = vel+accel;
			writeDebugStreamLine("velocidad : %d y accel: %d  ",vel, accel);
	}
}
